### ISSUE TITLE
Urgent issue: Version 4.2 do not build on Acceptance and Production environments

### ISSUE THREAD

**Issue by swkruger** [mendix/TreeViewAndGridView#21]
Hi,
I like your widgets and use them throughout my projects. It appears there was recently a critical issue fixed regarding the memory leak, and downloaded the latest version 4.2.

The new version 4.2 of the Gridview widget does not build in acceptance and production environments using Mendix 6.2.1. It builds and runs fine in the local environment using the same Mendix Modeler version.

Could you perhaps look at this urgently.

The only log trace I could get:
v6.2.1
ERROR: Could not build your widgets. This may be due to outdated widgets in your project.
You can check which widgets failed to build by clicking Tools > Check Widgets.
BUILD FAILED

**Comment by JelteMX** [comment]
Can you test [this version](https://github.com/mendix/TreeViewAndGridView/raw/master/dist/TreeView.mpk) and report back if it works?

**Comment by swkruger** [comment]
Thank you very much. The new version build and works perfectly! Thanks for the quick response and turn around

**Comment by JelteMX** [comment]
Thanks for testing 👍 . I have added the fixes in the new release [4.3.0](https://github.com/mendix/TreeViewAndGridView/releases/tag/v4.3.0), which is also updated in the AppStore right now
