### ISSUE TITLE
A number of deprecated function when converting to mx7

### ISSUE THREAD

**Issue by vietduc1441** [mendix/TreeViewAndGridView#27]
DEPRECATED: _Scriptable mixin will be removed in version 8.0. The mixin does not have any effect anymore. The only supported interface was 'close' and to continue offering it now, widget should just implement a method 'close(callback)'.
DEPRECATED: mendix.lang.nullExec. Use plain javascript if instead -- will be removed in version: 9.0 RenderNode.js RenderEdge.js
DEPRECATED: mx.data.save will be removed in version 8.0. The 'mx.data.save' function does not have any effect anymore. MxObjects are now automatically saved as part of 'mx.data.commit', 'mx.data.rollback', 'mx.data.action' and 'mx.data.saveDocument' treeView.js

**Comment by JelteMX** [comment]
Fixed in #31
